### ISSUE TITLE
no more stack trace in operator_new(_Znwj) on armeabi-v7a 

### ISSUE THREAD

**Issue by shenghanzhouyou** [bytedance/memory-leak-detector#1]
use libudf_unwind_backtrace(xframes, 2, STACKTRACEDEPTH) on hook _Znwj callback function 
the reuslt:

xHook ### allocated [12,679]K 12983343 allocCnt:2522 freeCnt:2003 by:
    ###00 0x00300135  _Znwj

only 1 frame!  no more???

**Comment by shentianzhou** [comment]
Dou you have a complete log?

**Comment by shentianzhou** [comment]
libudf_unwind_backtrace is a third-party library. The depth of the stack is affected by the runtime
