### ISSUE TITLE
最后输出结果的单位

### ISSUE THREAD

**Issue by Stephen-Adams** [bytedance/memory-leak-detector#10]
大佬，想问下，这个分析工具最后输出的统计数据的单位是字节数吗？
python library/src/main/python/raphael.py -r report -o leak-doubts.txt -s ./symbol/
![image](https://user-images.githubusercontent.com/24907251/122344292-37420c80-cf79-11eb-8975-1db2a4bfb03f.png)

**Comment by shentianzhou** [comment]
byte
