### ISSUE TITLE
为什么我在malloc和calloc中每次分配的是100M的内存，但是在report文件中只看到了37M的内存？

### ISSUE THREAD

**Issue by lijunhuawhu** [bytedance/memory-leak-detector#11]
你好，为什么我在malloc和calloc中每次分配的是100M的内存，但是在report文件中只看到了37M的内存呢？我看了多个系统版本的手机，都是这样？
![image](https://user-images.githubusercontent.com/7676643/124865176-c2e51100-dfec-11eb-9526-020db9b23358.png)

![image](https://user-images.githubusercontent.com/7676643/124865108-aba62380-dfec-11eb-9340-1e7956f199b7.png)

**Comment by shentianzhou** [comment]
这个是代码里存size时限定了26bit上限，100M的size溢出了，代码层面我们fix一下儿吧！

**Comment by shentianzhou** [comment]
0.1.5 fix

**Comment by lijunhuawhu** [comment]
> 0.1.5 fix

你好，我在demo上验证了一下，发现0.1.5还是没有修复
