### ISSUE TITLE
直接运行raphael.py脚本，提示 ModuleNotFoundError: No module named 'commands'

### ISSUE THREAD

**Issue by wsycomeon** [bytedance/memory-leak-detector#12]
![image](https://user-images.githubusercontent.com/15910433/126864197-d87233fd-a101-43ca-8ddf-5de18e6db159.png)

这个 commands 是 指哪个啊

**Comment by shentianzhou** [comment]
你的设备python里缺commands这个module，pip安装一下儿就可以了
