### ISSUE TITLE
raphael脚本增加-s参数报错

### ISSUE THREAD

**Issue by wustor** [bytedance/memory-leak-detector#14]
user$ python python/raphael.py -r raphael/report -o leak-doubts.txt  -s symbol/
Raphael script version: 1.0.0
{'libmapv2.so': '/Users/user/Documents/driver/libmapv2.so', 'libhawiinav.so': '/Users/user/Documents/driver/libhawiinav.so'}
Traceback (most recent call last):
  File "python/raphael.py", line 219, in <module>
    print_report(writer, report)
  File "python/raphael.py", line 151, in print_report
    retry_symbol(record)
  File "python/raphael.py", line 110, in retry_symbol
    symbol = addr_to_line(frame.pc, symbol_table.get(match.group(1)))
  File "python/raphael.py", line 88, in addr_to_line
    raise Exception('execute [/Users/user/Library/Android/sdk/ndk/21.1.6352462/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-addr2line -e %s -f %s] failed' % (symbol_path, address))
Exception: execute [/Users/user/Library/Android/sdk/ndk/21.1.6352462/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-addr2line -e /Users/user/Documents/driver/libmapv2.so -f 0x0017c91b] failed

**Comment by shentianzhou** [comment]
/Users/user/Library/Android/sdk/ndk/21.1.6352462/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-addr2line -e /Users/user/Documents/driver/libmapv2.so -f 0x0017c91b

这个命令执行失败了，你本地看看是不是arm-linux-androideabi-addr2line找不到
