### ISSUE TITLE
配置项的各个参数含义具体是什么

### ISSUE THREAD

**Issue by Cr321** [bytedance/memory-leak-detector#24]
Raphael.MAP64_MODE | Raphael.ALLOC_MODE | 0x0F0000 | 1024
前两个mode我大概可以猜到是什么，一个是监听 MMAP，一个是监听 ALLOC，查看源码我看到还有一个 DIFF_CACHE，这是什么含义？
后面的 0x0F0000 和 1024 又是配置的什么？

**Comment by shentianzhou** [comment]
- 低16位：拦截阈值配置（小于此值的不拦截，仅ALLOC模式生效，MAP64模式不受限制）
  - 20 - 16：栈回溯最大深度，最大栈回溯：min(32/16, 参数控制)
  - 第22位：Raphael.ALLOC_MODE，监控malloc、calloc、realloc、memalign、free等调用
  - 第23位：Raphael.MAP64_MODE，监控mmap、mmap64、munmap等调用
  - 其余位：未定义

**Comment by Cr321** [comment]
> * 低16位：拦截阈值配置（小于此值的不拦截，仅ALLOC模式生效，MAP64模式不受限制）
> * 20 - 16：栈回溯最大深度，最大栈回溯：min(32/16, 参数控制)
> * 第22位：Raphael.ALLOC_MODE，监控malloc、calloc、realloc、memalign、free等调用
> * 第23位：Raphael.MAP64_MODE，监控mmap、mmap64、munmap等调用
> * 其余位：未定义

Thanks
