### ISSUE TITLE
【必现】线程卡住问题

### ISSUE THREAD

**Issue by hansweidong** [bytedance/memory-leak-detector#29]
MemoryCache.cpp 中
pthread_mutex_lock(&alloc_mutex);
    for (auto p : alloc_table) {
        for (; p != nullptr; p = p->next) {
            write_trace(report, p, nullptr, &dl_cache);
        }
    }
 pthread_mutex_lock(&alloc_mutex);

pthread_mutex_lock(&alloc_mutex);
在调试中发现这句代码卡住线程

**Comment by shentianzhou** [comment]
什么机型？

**Comment by zhoujunyou** [comment]
我这边也必现，怎么两个pthread_mutex_lock，  不应该是pthread_mutex_unlock吗。

**Comment by shentianzhou** [comment]
确实是这个问题
