### ISSUE TITLE
这只是权限的问题吗？

### ISSUE THREAD

**Issue by AheadSnail** [bytedance/memory-leak-detector#38]
<img width="1399" alt="image" src="https://user-images.githubusercontent.com/30452983/198326764-7f9a4926-0182-4caa-bf10-b67407aeb428.png">

**Comment by AheadSnail** [comment]
发现给了SDK 卡权限也是不行

**Comment by shentianzhou** [comment]
先看原来是不是就有这个路径，删除再试试。
