### ISSUE TITLE
 MemoryCache::insert  Alloc cache is cause anr please help me

### ISSUE THREAD

**Issue by chongbo2013** [bytedance/memory-leak-detector#7]
![image](https://user-images.githubusercontent.com/3191545/121486568-d6a85200-ca03-11eb-9ef5-5515d19a1fdc.png)
Alloc cache is full!!!!!!!! anr.pls

**Comment by shentianzhou** [comment]
缓存耗完这个版本没有处理好，后续版本里已经优化了，我们最近会同步出来

**Comment by chongbo2013** [comment]
@shentianzhou 还有个问题，当不是在application里初始化的时候，会漏掉之前的so
是否第一次初始化的时候，通过proc/self/map来手动加载hook，一次，然后再开启so加载监听hook， 保证后面加进来的也可以。

**Comment by chongbo2013** [comment]
@shentianzhou 你好，大概什么时候同步出来

**Comment by shentianzhou** [comment]
7月中下旬吧！
